version: '2'
services:
  db:
    image: postgres:10.4
    container_name: fhirbase
    volumes:
       - .data:/var/lib/postgresql/data
    ports:
      - "${PGPORT}:5432"
    environment:
      POSTGRES_USER: ${PGUSER}
      POSTGRES_PASSWORD: ${PGPASSWORD}
      POSTGRES_DB:   ${PGDATABASE}